# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Оргкомитет ОСМД Французский
title2: Оргкомитет ОСМД Французский который подготавливает Общее Собрание
tagline: Подготавливаем Общее Собрание
lang: ru
email: orgkomitet.osmd.fran@gmail.com

description: 65058 Одесса, Французский бульвар 22 корпуса 1/2/3/4/5.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://orgkomitet-osmd-fran.org" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: false
logo: /favicon-200x200.png

google_analytics: UA-193279840-1
# google_site_verification


twitter_username: OSMD_Frants
facebook_username: groups/1692908524359966
# instagram_username
# github_username:

twitter:
   card: summary
   username: OSMD_Frants

facebook:
   publisher: https://www.facebook.com/groups/osmd.frantsuzskiy/ # a Facebook page URL or ID of the publishing entity
#  app_id: 1234
#  admins: 1234

social:
   name: Оргкомитет ОСМД Французский # If the user or organization name differs from the site's name
   links:
      - https://www.facebook.com/groups/osmd.frantsuzskiy
      - https://twitter.com/OSMD_Frants

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
  toc_levels: "2,3,4"

theme: minima
plugins:
   - jekyll-seo-tag
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

prose:
  media: 'assets'
  rooturl: "_posts"
#  siteurl: "https://orgkomitet-osmd-fran.org/"
  ignore:
    - .bundle
    - _config.yml
    - .gitignore
    - CNAME
    - index.md
    - Gemfile
    - Gemfile.lock
    - site.webmanifest
    - 404.html
    - /_layouts
    - /_includes
    - /_site
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "page2"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
          help: "Опционально - относительная ссылка/URL этой статьи (Permanent link). Будет использована вместо ссылки/URL сгенерированной автоматически. Например /otkaz-ot-otvetstvennosti/"
      - name: "description"
        field:
          element: "text"
          label: "description"
          value: ""
          help: "Опционально - небольшой текст который длиннее заголовока, обычно до 2х-3х строчек. Текст кратко поясняет содержимое страницы. Вместе с заголовком этот текст будет показан в результатах Google Search."
      - name: "image"
        field:
          element: "text"
          label: "image"
          value: ""
          help: "Опционально - относительная ссылка на картинку вверху страницы. Например /assets/720x200.png"
      - name: "show_in_articles"
        field:
          element: "checkbox"
          label: "Show in articles"
          help: "Показывать ли статью в списке СТАТЕЙ на главной странице?"
          value: false
      - name: "show_in_documents"
        field:
          element: "checkbox"
          label: "Show in documents"
          help: "Показывать ли статью в списке ДОКУМЕНТОВ на главной странице ?"
          value: false

